---
title: "Surry-Activity-1"
author: "Liam Surry"
date: "2024-09-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **1. Main Area of Research** 
There is currently a drug crisis with **devastating** socioeconomic impacts. My research interest involves optimizing and applying a capillary electrophoresis mass-spectromety (CE-MS) based approach for large-scale screening of illicit, over-the-counter, and prescription drugs in high-risk populations (low income, homeless,etc). Currently, data pre-processing is **extremely time intensive**, hampering CE-MS's ability for real-world application in the field. My goal is to optimize an existing data-processing script and create a user friendly user interface in addition to optimizing the script to accurately identify drugs and their metabolites. This script will then be applied to a large cohort and extensively tested before being applied in the field. Additionally I will be working with psychiatrists to assess what they desire in such a platform. 

# **2. Favourites**
## *2.1 Favourite Music*
1. Even in the Quietest Moments - Supertramp
1. Feels So Good - Chuck Mangione
1. City of Stars - Justin Hurwiz
1. Goddess - Laufey
1. Le festin - Michael Giacchino

## *2.2 Favourite equation*
$$
x = \frac{-b\pm \sqrt{b^2-4ac}}{2a}  
$$

## *2.3 Favourite Artists*
Name | Achievements
-|-
Justin Hurwiz | Composer of the musical score for La La land
Hanz Zimmmer | One of the best movie composers, e.g. composition of "Time"
Chuck Mangione | Got #4 on the Billboard Hot 100 chart in 1978 as a jazz musician   playing a flugelhorn (never happened before, probably will never happen again) 
Bob Ross | Master of painting and sharing the joy of painting 
Euthymides | Ancient athenian potter and painter of vases famous for painting the vases such as "Achilles and Ajax"

# **3. A Chunk of Code**
```r
groceries<- c(1,2,3,4,5)
cost_dollars <- c(4.99, 2.49, 0.99, 4.99, 13.99)
plot(groceries, cost_dollars)
```
